server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

